title: "Smart Mobility Research Atlas"
description: "A structured research atlas of the Smart Mobility Lab at Penn State"

baseurl: "/smart-mobility-atlas"
url: "https://xbhu.github.io"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

# Collections
collections:
  papers:
    output: true
    permalink: /papers/:name/

# Default layouts
defaults:
  - scope:
      path: ""
      type: papers
    values:
      layout: paper
